### ISSUE TITLE
KeyType permits `..`

### ISSUE THREAD

**Issue by byrongibby** [sdmx-twg/sdmx-rest#105]
Hi

I am trying to acquaint myself with the API and I am not sure how the following should be dealt with:

https://demo.metadatatechnology.com/FusionRegistry/ws/public/sdmxapi/rest/data/ECB,EXR,1.0/..?format=sdmx-compact-2.1

resolves to

https://demo.metadatatechnology.com/FusionRegistry/ws/public/sdmxapi/rest/data/?format=sdmx-compact-2.1

which returns error code `150` whereas I think the intention is that should return all?

**Comment by agent96** [comment]
Yes, you are correct - this should return all not an error code.

**Comment by byrongibby** [comment]
Thanks. I'll work around it.

**Comment by agent96** [comment]
Sorry, I misinformed you in my previous response.  In a URL '..' is always resolved to 'back up a level' in the path, there is nothing we can do to change that. To give an example, the following URL
https://google.com/broken/..

Resolves to 
https://google.com

As the .. removes the '/broken' part of the URL from the path.  The strange concequence of this is that for a DSD with only 2 Dimenisons, the use of '..' to mean all will not work, as the URL it resolves to removes the path which includes the Dataflow parameters.  I would always recommend using the keyword 'all' when there are no dimenison filters.
https://demo.metadatatechnology.com/FusionRegistry/ws/public/sdmxapi/rest/data/ECB,EXR,1.0/all

You can also not have any arguments, which also resolves to all:
https://demo.metadatatechnology.com/FusionRegistry/ws/public/sdmxapi/rest/data/ECB,EXR,1.0/

My misunderstanding was that I did not see that your second URL had removed the Dataflow identifiers (ECB,EXR,1.0) from the path:
https://demo.metadatatechnology.com/FusionRegistry/ws/public/sdmxapi/rest/data

This is not a valid query, as the Dataflow identifiers are required for a data query.

**Comment by byrongibby** [comment]
Yes. I am trying to build my own SDMX REST API and my toy DSD happened to have two dimensions which is how I ran into the issue. My router gives 404 for keys `.` and `..`. The former drops that part of the path (stay at current level) and the latter moves up a level in the path (as you mention). In both cases the *resolved URL* does not conform to the {flowRef}/{key}/{providerRef} spec.

The main problem I see is that third-parties connecting to my API will not know that they should use the `all` keyword or omit that part of the path (to wild card all dimensions). Maybe your recommendation should be made explicit in the docs (if it isn't already). That said, not many DSDs are going to have 2 or 3 dimensions.

Thanks again for your assistance.
