### ISSUE TITLE
rest api or soap service Link ?

### ISSUE THREAD

**Issue by sametturel** [sdmx-twg/sdmx-rest#138]
I could not find a REST API or SOAP service link ?

**Comment by sosna** [comment]
This repository hosts the SDMX specification, and not the list of implementations. The Wiki list a few existing implementations, but it is not meant to be comprehensive: https://github.com/sdmx-twg/sdmx-rest/wiki/Where-is-it-used. If this is not what you meant, please let us know.

**Comment by sametturel** [comment]
Thank you for feedback,

I want that;
-Exchange rate for all countries  
(sample : EUR-USD 1.78, EUR-GBP 2.0 , EUR-TRY 2.5 vs.... )

-Date based Exchange rate for all countries 
(sample 01.01.2021 EUR-USD 1.78, EUR-GBP 2.0 , EUR-TRY 2.5 vs....)
(sample 02.01.2021 EUR-USD 1.78, EUR-GBP 2.0 , EUR-TRY 2.5 vs....)
(sample 03.01.2021 EUR-USD 1.78, EUR-GBP 2.0 , EUR-TRY 2.5 vs....)
(sample 04.01.2021 EUR-USD 1.78, EUR-GBP 2.0 , EUR-TRY 2.5 vs....)

webservice link where I can get this information.

**Comment by sosna** [comment]
OK, as mentioned, maybe the [Where is it used?](https://github.com/sdmx-twg/sdmx-rest/wiki/Where-is-it-used) page on the Wiki will help (some of the implementers like the ECB might have what you need).

But this repository is for managing the official API specification (i.e. the spec to be used by the various implementers) and so I will close your issue as it is not related to the API itself.
