### ISSUE TITLE
Data queries example point to 502

### ISSUE THREAD

**Issue by SirArtorias** [sdmx-twg/sdmx-rest#142]
Hi there, while I was looking for a way to get the "base rate by civil code" out of your API I noticed that the examples in the https://github.com/sdmx-twg/sdmx-rest/wiki/Data-queries section are causing a 502 HTTP-Response.

**Comment by Tzaphkiel** [comment]
I see references to the `ecb.int` domain. I believe it should be `.ecb.europa.eu` instead.
Also remove the `a-` at the beginning of the URI. This then points to the (more stable) production service and not the acceptance one.
i.e.: https://sdw-wsrest.ecb.europa.eu/service/data/EXR/M.USD.EUR.SP00.A
