### ISSUE TITLE
DataType for component value(s)

### ISSUE THREAD

**Issue by eric-basley** [sdmx-twg/sdmx-rest#150]
In SDMX3.0 https://github.com/sdmx-twg/sdmx-rest/blob/develop/doc/data.md doc, it lacks the way to identify the type a a component values, neither dataType nor  textType are mentionned, first is mentioned in samples.

Can U precise this point ?

regards

**Comment by dosse** [comment]
@eric-basley There would be two ways of obtaining this information:  

1) Before requesting data, make a request to retrieve the underlying data structure definition (directly or through references). This will contain the types (representations) for all components: dimensions, attributes and measures.
2) When retrieving the data in SDMX-JSON format, the response includes now also the types (representations) of the components in its structural information part (see the [format](https://github.com/sdmx-twg/sdmx-json/blob/sdmx3.0.0/data-message/docs/1-sdmx-json-field-guide.md#format) property of the [components](https://github.com/sdmx-twg/sdmx-json/blob/sdmx3.0.0/data-message/docs/1-sdmx-json-field-guide.md#component)). 

[Please note that very soon the sdmx3.0.0 branch will be merged into the develop branch and the links might need updating.]

**Comment by eric-basley** [comment]
Yes but the point is that format property do not mention  'dataType' in the spec where as samples format objects have a dataType prop.
Is it a lack in the spec ?

**Comment by dosse** [comment]
I'm a bit confused. Which spec do you mean? 

The component's new format object in SDMX-JSON data messages has the following properties defined:

- minOccurs 
- maxOccurs 
- textFormat <-- This contains the underlying data type
- minLength
- maxLength
- minValue
- maxValue
- pattern
- isMultiLingual
- sentinels

#### Examples:

	"format": { 
		"minOccurs": 2,
		"maxOccurs": 2,
		"textFormat": "Double",
		"isMultilingual": false,
		"sentinels": [
			{
				# sentinel value object #
			}
		]
	}

	"format": { 
		"minOccurs": 2,
		"maxOccurs": 3,
		"textFormat": "String",
		"minLength": 4, 
		"maxLength": 4, 
		"pattern": "^[A-Za-z][A-Za-z0-9_-]*$",
		"isMultilingual": true
	}

**Comment by eric-basley** [comment]
Thanks for your precisions, because samples like https://github.com/sdmx-twg/sdmx-json/blob/sdmx3.0.0/data-message/samples/constructed-sample-full.json is still using 'dataType' instead of 'textFormat'.

The domain value of textFormat is not defined in https://github.com/sdmx-twg/sdmx-json/blob/sdmx3.0.0/data-message/docs/1-sdmx-json-field-guide.md

**Comment by dosse** [comment]
@eric-basley Thank you for spotting this issue. The linked documentation and also the example given by me here above should have used 'dataType' instead of 'textFormat'. 

	"format": { 
		"minOccurs": 2,
		"maxOccurs": 2,
		"dataType": "Double",
		"isMultilingual": false,
		"sentinels": [
			{
				# sentinel value object #
			}
		]
	}

	"format": { 
		"minOccurs": 2,
		"maxOccurs": 3,
		"dataType": "String",
		"minLength": 4, 
		"maxLength": 4, 
		"pattern": "^[A-Za-z][A-Za-z0-9_-]*$",
		"isMultilingual": true
	}

The documentation has been updated.

**Comment by sosna** [comment]
Fixed as part of the sdmx-json work
