### ISSUE TITLE
Add response messages to the API

### ISSUE THREAD

**Issue by dmolinaj** [sdmx-twg/sdmx-rest#152]
The open api doc only has status codes as response message. When define the API in our own products we are only able to get code & the header. The body/messagedata is not defined in the response

**Comment by sosna** [comment]
(Note to self before the analysis starts: This is not trivial for the structure specific formats)

**Comment by sosna** [comment]
We have decided to close this issue. Some formats don't support a schema (e.g. csv). We can’t support any of the structure-specific formats either, which would rule out support for pretty much all data message. Some messages (e.g. the structure message) can be supported, but, as it is only a small subset, the benefits are unclear.
