### ISSUE TITLE
Fix structureType issues in yaml

### ISSUE THREAD

**Issue by achronis** [sdmx-twg/sdmx-rest#160]
Hi,

In the 2.0.0 yaml file, at the structureType enum might contain an invalid `structureset` and it is misses `reportingtaxonomy`

https://github.com/sdmx-twg/sdmx-rest/blob/master/api/sdmx-rest.yaml#L281

**Comment by stratosn** [comment]
Thanks @achronis, I quickly cross-checked and it looks like an issue, indeed.
We will assess this within the TWG and let you know.
cc: @sosna

**Comment by sosna** [comment]
Fixed in the `develop` branch

**Comment by sosna** [comment]
Fixed in v2.1.0
