### ISSUE TITLE
Dataflow query using referencepartial seems to ignore a constraint attached to DSD

### ISSUE THREAD

**Issue by viguice** [sdmx-twg/sdmx-rest#162]
When I retrieve the following query (http://myserver/sdmx/v2/structure/dataflow/myagency/mydataflow/latest/?format=sdmx-3.0&detail=referencepartial&references=all), the codelists are correctly constrained by the constraint attached on the dataflow but not on the one attached to the DSD. The DSD constraint is not even reported in the DataConstraints section.
In my view, the use of referencepartial option should combine all different constraints on all possible levels (provision, data provider, dataflow and data structure) to know which codes have to been displayed.

**Comment by sosna** [comment]
Thanks for reporting this. 

I assume you are referring to the REST specification, and not to any implementation of it. 

Provided I understood your use case correctly, then the `schema` query might be a better fit, as this is the query that will apply constraints, taking the cascading rules into account.

Performing a query for structures (e.g. `dataflow`) and then settings `detail` to `referencepartial` and `references` to `all` has a different meaning and is not intended to "constrain" codelists. What it does is the following:

1. With `references=all`, the response must include the descendants (e.g. DSD and then codelists and concept schemes), as well as the parents and siblings (e.g. DataConstraint) of the requested dataflow.
2. With `detail=referencepartial`, the response must only include the items that are referenced in the artefacts returned by point 1 above. For example, the concept scheme must only contain the subset of concepts used in that particular dataflow. Or the codelists must only include the codes referenced by the constraints returned in the response. However, this is not the same as constraining the codelists as, after all, the referenced codes could be marked as being included or as being excluded. Again, if you need that functionality, you should look at [schema queries](https://github.com/sdmx-twg/sdmx-rest/blob/master/doc/schema.md).

**Comment by viguice** [comment]
Hi Xavier,

Sorry, I am not really following you. It still looks to me as a bug. I include a file with structures for illustration.
I have here one DSD _DSD_BCS_PROD_ with the _CS_DSD_BCS_PROD_ constraint attached to it.
On top of it, I have a dataflow _DF_BCS_PROD_BUIL_ with the _CS_DF_BCS_BUIL_PROD_  constraint.

If I query the DSD (sdmx/v2/structure/datastructure/all/all/latest/?format=sdmx-3.0&references=all), it is working well. I receive exactly what I expect. Indeed I receive the descendants as well as the parents and siblings (e.g. DataConstraint) of the requested DSD. Thus the query for partial result (/sdmx/v2/structure/datastructure/all/all/latest/?format=sdmx-3.0&detail=referencepartial&references=all) is restraining correctly the _FREQ_ and _GEO_ codelists.

But if I query the Dataflow (/FusionRegistry/sdmx/v2/structure/dataflow/all/all/latest/?format=sdmx-3.0&references=all), only the constraint for the dataflow is reported and not the constraint on the DSD. In my view, there are two active constraints applicable on this dataflow and both constraints must be reported.
The query sdmx/v2/structure/dataflow/all/all/latest/?format=sdmx-3.0&detail=referencepartial&references=all is constraining correctly the _INDICATOR_ codelist but missed to constraint _FREQ_ and _GEO_  even if they are constrained for all dataflows attached to this DSD.
The references=all should also report the siblings of descendants because they impact also the current structure because the contraints are cumulative.





[BCS_Structures.zip](https://github.com/sdmx-twg/sdmx-rest/files/8284482/BCS_Structures.zip)

**Comment by agent96** [comment]
If a constraint is linked to a DSD then this is not expected to be in the response message when the query is for a dataflow with references=all.

To explain:
references=all will obtain the structures which reference the Dataflow (returning 1 constraint) and the descendants of the Dataflow (DSD/Concepts/Codelists).  It will also get the child structures of the Constraint.  It will not resolve parent structures of the descendants, i.e. it will not get the Constraint which references the DSD.

> "In my view, the use of referencepartial option should combine all different constraints on all possible levels (provision, data provider, dataflow and data structure) to know which codes have to been displayed."

The referencepartial tells the system to include all items in itemschemes (Codelist/Concepts) if they are referenced in the response - i.e. if your constraint is restricting the value UK in the REF_AREA codelist then the codelist will be made partial regardless of whether the constraint rule is to say UK must be reported or UK must NOT be reported.  As such it is not a good mechanism to determine what the valid values are for data reporting.  If you want the final set of valid values after applying all constraints in the context of a Dataflow - then you should use the schema query but ask for the response as a SDMX structure message, this will return a constraint which is generated by combining all the restrictions at all levels.   If you ask for references=descendants then it will include partial Codelists and Concept Schemes - made partial by applying the rules on what can reported against the Dataflow.

**Comment by viguice** [comment]
Thanks Matt and Xavier,

That is awesome. the query sdmx/v2/schema/dataflow/ECFIN/DF_BCS_PROD_BUIL/1.0/?format=sdmx-3.0&structure=true is indeed returning what I was expecting.
Sorry for bothering you with such kind of questions but maybe a forum where we can just post questions and check if it has already been answered would help newbies as me in the learning curve ;-).

I take this opportunity for asking something else. I am trying to renovate my statistical production system by something based on SDMX with a more metadata driven approach.
I have created hierarchical codelist HGEO (see zip file). I would like to create a query for getting all children or all parents of a specific code. For example, parents of BE is EU and EA, BG is only EU, AL is nothing. Another type of query would return children for example the list of EU or EA member states respectively. this will be used for listing all possible derivations of a raw timeseries to see what has to recalculated just by analyzing the information stored whithin the registry.
I didn't find the way to extract this information right away from the API. Did I miss something? I could obviously program get_parents and get_children functions by myself after loading the full codelist but I was wondering if it is possible to retrieve directly this information from the API.

**Comment by dosse** [comment]
There might be some additional information useful for this topic. 

When the `referencepartial` parameter was introduced, which was before the release of SDMX 3.0, and before the definition of data availability, there was indeed an unfortunate diverging comprehension of the meaning of this parameter in the TWG. Some members understood to:  
1) restrict the item schemes to items mentioned in other related referencing artefacts, like content constraints.   
Other members understood to:  
2) restrict the item schemes to valid items in the current context, taking into account related referencing artefacts like allowed content constraints, which thus could concern both DSD and dataflow-related allowed content constraints if they both constrain the requested dataflow. 

Different SDMX solutions have thus implemented one or the other approach. The SDMX web service instance that you are mentioning here seems having implemented the first approach. In practice, the difference is appearing only when using : 
- excluded items in allowed content constraints (this doesn't seem being a frequently used feature)
- allowed content constraints on data structure definitions (this also doesn't seem too widely used yet)

The final approach was then clarified for SDMX 3.0, which actually is the first one, however implementations of the second approach continue using their implementation for SDMX 2.1 and will switch to the first approach only when migrating to SDMX 3.0. But as mentioned, in case you use a solution implementing SDMX 2.1 with the first approach, they provide your required functionality through the schema queries.

**Comment by sosna** [comment]
Closing issue as question has been answered
