### ISSUE TITLE
Handling of large Codelists (ItemSchemes in general?) - Pagination?

### ISSUE THREAD

**Issue by buhaiovos** [sdmx-twg/sdmx-rest#173]
Hello!

Preemptively sorry in case this is a wrong communication channel. Are there any plans or maybe some approaches that already exist to handle queries for large codelists? Let's say we have a client-app that due to some limitations has issues dealing with a codelist that has a couple of millions of codes. Are there any "right" ways to implement partial request for a portion of a codelist to do some kind of pagination/lazy load of the codelist's contents?

Thanks!

**Comment by sosna** [comment]
As this is more of a question, it has been moved to the [Discussions section](https://github.com/sdmx-twg/sdmx-rest/discussions/175).
