### ISSUE TITLE
SDMX REST cheat sheets

### ISSUE THREAD

**Issue by stratosn** [sdmx-twg/sdmx-rest#179]
Since the release of the v2.0.0 API the "RESTful web services cheat sheet" for older versions of the API are not easily accessible.
For example, for v1.5.0, you need to get to it through the corresponding tag: https://github.com/sdmx-twg/sdmx-rest/blob/v1.5.0/v2_1/ws/rest/docs/rest_cheat_sheet.pdf

It would be convenient for the user to be able to get to the previous (maybe major) versions from the `README.md` file of the master branch, especially because the location of the cheat sheet might change, making in it harder to access.

**Comment by sosna** [comment]
Hi @stratosn. I'm not sure to understand what is required here, considering the fact there is a tag associated with each release and it possible to browse the state of the repo as it was at any particular tag... Could you please clarify?

**Comment by sosna** [comment]
Fixed by https://github.com/sdmx-twg/sdmx-rest/pull/204
