### ISSUE TITLE
Data query `attributes=all/msd` underspecified

### ISSUE THREAD

**Issue by hoehrmann** [sdmx-twg/sdmx-rest#194]
https://github.com/sdmx-twg/sdmx-rest/blob/99e92fd7a7f2c1a0c5dcfb2776f2fdae3cf2458e/doc/data.md specifies a parameter `attributes` that can take various values. I cannot make sense of the `all` (and implictly `msd`) value for it. I may be way off here, but for me problems include:

* As far as I know, DSD and MSD do not share a namespace. You can have a COMMENT attribute in each of them, and `attributes=all` would have an implementation report both of them, but since they have the same name, and some formats like SDMX-CSV support identification by name only, the result of such a query may have no valid representation.
* I have been unable to find a requirement in the SDMX-IM that implies a DSD is linked to at most 1 MSD. So it seems the attributes in a response to such a query might even come from many MSDs.
* Values for the MSD attributes do not come from the MSD but from metadata reports. As far as I can tell, there can be many reports that apply to a given DSD, and there is no indication how to choose from the many options for a given data query.
* Existing implementations apparently require proprietary extra steps for them to accept metadata uploads, https://sis-cc.gitlab.io/dotstatsuite-documentation/using-dlm/manage-data/upload-data/upload-data-and-metadata/#prerequisites for instance requires a `METADATA` annotation on the DSD, which solves part of the problem (there then is only a single MSD linked to a DSD), but independent implementers have no way of knowing this from the SDMX specifications.

Substantial clarification on how to implement this feature needs to be added, to allow for independent and interoperable implementations.

(In doubt, please handle this as a public review comment on SDMX 3.1 once the comment period begins.)

Edit: I have since found that a data structure can reference zero or one metadata structure. Then I am guessing the `METADATA` annotation method might be a historical workaround for the lack of this feature.

**Comment by agent96** [comment]
On your first bullet point: I believe we may need to add a clarification on how systems handle Attributes that are present in both a DSD and MSD in this context.  I would suggest a DSD should not be able to extend its attributes with that from an MSD if there is a conflict (i.e. 2 Components with the same ID). This will need to be revised in the Technical Notes during the 3.1.0 revision.

On your second bullet point: You are correct in your edit, a DSD can reference only 1 MSD as specified in "SDMX Standards: Section 2 - Information Model" subsection 5.3.1.  

https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_2_FINAL-1_0.pdf

On your third bullet point: The purpose of a DSD referencing an MSD is to extend the attributes of a DSD, incorporating those of the MSD and DSD as a union.  In this context, the Attributes for both the DSD and MSD are reported in a dataset, allowing the information to move in one single package, they are not separated into Dataset and Metadata Report.  The Metadata Report is only relevant if the MSD is attached to a structure, for example a Dataflow, Code, Concept, or other.

This behaviour is defined in "SDMX Standards: Section 6 - Technical Notes"

https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_6_FINAL-1_0.pdf
```
1110 An important change of SDMX 3.0 is the ability to reference an MSD within a DSD, in
1111 order to report any Metadata Attributes defined in the former to Datasets of the latter.
1112 This is achieved by the following:
1113 • In a DSD, the user may add a reference to one MSD.
1114 • In the Attribute Descriptor of the DSD, the user may include any Metadata
1115 Attributes defined in the linked MSD.
1116 o For each link to a Metadata Attribute, an Attribute Relationship may be
1117 specified (similarly to that for Data Attributes).
1118 • In any Dataset complying with this DSD, Metadata Attributes may be reported
1119 according to the specified Attribute Relationship.
1120 o The hierarchy of the Metadata Attributes defined in the MSD must be
1121 respected and they are reported in the same way as in a Metadataset,
1122 under the level they are related within the DSD, via their Attribute
1123 Relationship.
```

On your last bullet point: I cannot comment on how other have implemented their systems.  However, the standard is that when a DSD uses a MSD, it is possible to combine both Metadata Attribute and Data Attributes in one message (the Dataset) and this allows data reporters to report both at the same time, or separately under the same message type, and it allows the dissemination to disseminate both under the same message.  

To add clarity to the REST API we can add some examples demonstrating the expected output under different selection scenarios.

**Comment by dosse** [comment]
@hoehrmann About your last comment
> Existing implementations apparently require proprietary extra steps for them to accept metadata uploads, [https://sis-cc.gitlab.io/dotstatsuite-documentation/using-dlm/manage-data/upload-data/upload-data-and-metadata/#prerequisites](https://sis-cc.gitlab.io/dotstatsuite-documentation/using-dlm/manage-data/upload-data/upload-data-and-metadata/#prerequisites) for instance requires a METADATA annotation on the DSD

Please note that, as documented [here](https://sis-cc.gitlab.io/dotstatsuite-documentation/using-api/ref-metadata/#introduction), while the .Stat Suite implementation "_uses the logical approach of the SDMX v3.0 Information Model for attaching referential metadata to data through an extension of the components defined in the Data Structure Definition (DSD) by referential metadata attributes defined in a Metadata Structure Definition (MSD), currently **it continues to use the structures defined with the SDMX v2.1 Information Model. Therefore, instead of the in-built link between DSD and MSD in SDMX 3.0, .Stat Suite uses a specific DSD annotation.**_" The annotation represents thus a temporary workaround solution while waiting for the NSI web service to support SDMX 3.0 structures.

I wonder why you say that "_I have been unable to find a requirement in the SDMX-IM that implies a DSD is linked to at most 1 MSD._". In addition to the citation by @agent96, also the [IM](https://sdmx.org/wp-content/uploads/SDMX_3-0-0_SECTION_2_FINAL-1_0.pdf) itself states on page 75:

<img alt="image" src="https://github.com/user-attachments/assets/7e83e642-a331-4f4e-9bff-8fb3d085862e">   

> 1294 by a Dataflow. In addition, a DataStructureDefinition may be related to **one**
> 1295 MetadataStructureDefinition, in order to use the latter’s MetadataAttributes, by
> 1296 relating them to other Components within the DSD, as explained below.

Could you please clarify, where the confusion comes from, so that we can improve the documentation?

**Comment by sosna** [comment]
Closed because of lack of activity. Please reopen in case the issue is still relevant. Thank you.
