### ISSUE TITLE
`dimensionAtObservation=TimeDimension` or `dimensionAtObservation=TIME_PERIOD`

### ISSUE THREAD

**Issue by hoehrmann** [sdmx-twg/sdmx-rest#198]
In https://github.com/sdmx-twg/sdmx-rest/blob/4ce8a59a1edf56189853f879141cd329689a4a21/doc/data.md the specification says that one option for the value of the `dimensionAtObservation` parameter is `TIME_PERIOD` but later says it should default to `TimeDimension` which is pretty much the same concept by a different name.

**Comment by sosna** [comment]
Thanks, @hoehrmann, the documentation will be corrected in the upcoming release.
