### ISSUE TITLE
Proposal: document valid component operators for Time Dimension and other components

### ISSUE THREAD

**Issue by achronis** [sdmx-twg/sdmx-rest#200]
Hello,

Do you think it would be useful to document the valid operators for Time Dimension ?
Mostly to help implementers, and to avoid possibly implementations with invalid combinations. 

Example ( could be incorrect)

The following table lists the valid operators for Time Dimension (`c[TIME_PERIOD]`)

| Operator | Rule | Example (Period: 2005-01) |
| --- | --- | --- |
| Greater Than (gt) | Any data after the last moment of the period | "> 2005-01-31" |
| Less Than (lt) | Any data before the first moment of the period | "< 2005-01-01" |
| Greater Than or Equal To (ge) | Any data on or after the first moment of the period | ">= 2005-01-01" |
| Less Than or Equal To (le) | Any data on or before the last moment of the period | "<= 2005-01-31" |
| Equal To | Any data which falls on or after the first moment of the period and before or on the last moment of the period | ">= 2005-01-01 and <= 2005-01-31" |

**Comment by sosna** [comment]
Thanks for the proposal, @achronis. 

I asked implementers around and, actually, several of us don't see a need to restrict the list of operators when the component is `TIME_PERIOD`. Some of these operators indeed look useful to support certain use cases, such as, for example:

- `c[TIME_PERIOD]=co:Q1`, to indicate that you want data from the first quarter of any year.
- `c[TIME_PERIOD]=sw:2024`, to indicate that you want data from any period in 2024.

Of course, , if a service decides not to support some of these operators for time periods, that is fine, provided it returns a `501` (“Not implemented”) error. At the same time, we would not like to forbid somebody from supporting such operators if he finds them useful.
