### ISSUE TITLE
Download in CSV format via curl

### ISSUE THREAD

**Issue by flavio-greenfact** [sdmx-twg/sdmx-rest#202]
Hi, 

I tried to follow the example in the website, however it does not work, I got the error:

curl -k -o data.csv https://data-api.ecb.europa.eu/service/data/FM.B.U2.EUR.4F.KR.MRR_FR.LEV?format=csvdata

no matches found

If I remove the format=csvdata, I get a message: Request blocked.

**Comment by sosna** [comment]
This is the repository used to maintain the SDMX-REST **specification**. 

For questions or bug reports about a concrete implementation of the specification (like the  Eurostat one in this case), please contact the implementer directly. Thank you 😊
