### ISSUE TITLE
Document behaviour on the  output for query data by Data Structure / Provision Agreement

### ISSUE THREAD

**Issue by agent96** [sdmx-twg/sdmx-rest#203]
the V2.x API allows a data query to be performed at the level of the DSD / Dataflow / Provision Agreement, but the output is not defined which makes it open to interpretation.  

For example:

`/datastructure/IMF,ECOFIN/* `

This could be interpreted to return 1 Dataset across all Dataflows where the header links to the DSD or does it return 'n' number of Datasets where each one links to its own Dataflow.

`/provisionagreement/UK_BOP/*`

Could return 1 Dataset with the Dataflow URN in the header, or 1 Dataset with the Provision Agreement URN in the header.

`/provisionagreement/UK_BOP/*`

Additionally, the default is '*',  could this result in multiple datasets at the level of the data structure or should it be output at the level of the dataflow?

**Comment by sosna** [comment]
Thanks, @agent96. IMO, the service should **respect the requested context type**. 

If the client sets the context to `datastructure`, then we should have one dataset per matching data structure. Likewise, if the client sets the context to `provisionagreement`, we should have one dataset per matching provision agreement. 

Personally, if I set the context to `provisionagreement`, I am not expecting the service to group the data per dataflow. If that is what I wanted, I would have set the context to `dataflow` instead. 

What do you think?

**Comment by sosna** [comment]
Fixed in PR #217
