### ISSUE TITLE
Confirm if sort includes attributes and measures

### ISSUE THREAD

**Issue by agent96** [sdmx-twg/sdmx-rest#230]
In the REST API spec for data it is not clear if the sort parameter can apply to attributes and measures.  There is one sentence 

"This parameter specifies the order in which the returned data should be sorted. It contains either one or more **component** IDs"

This is the only time attributes and measures are (indirectly) documented, with the rest of the documentation and examples referring to dimensions.  It would be helpful to add an explicit statement to this to ensure there is no ambiguity.

**Comment by sosna** [comment]
Fix by #235
