### ISSUE TITLE
New format & version parameters (to avoid custom solutions)

### ISSUE THREAD

**Issue by tasosc** [sdmx-twg/sdmx-rest#36]
Some short introduction to the issue. We (SDMX RI )  got a request for specifying the format/version from the URL and at the same time we see different solutions/approaches from various organisations e.g. from ISTAT (some kind of wrapper Service to StructureSpecificData) and Global Registry (version parameter).

Based on the above I assume there are use cases where setting the HTTP header Accept is not easy or not possible. Example on browsers without a REST plugin or using software that doesn't support this and cannot be easily modified.

In order to avoid having different custom solutions for specifying format/version without a HTTP Accept header, it might be better to have a common approach, i.e. one or two  new parameters for data and structure requests in SDMX REST.
For example:

| Parameter | Description |
| --- | --- |
| format | Whatever [format].[xml/json/whatever]  is supported via Accept. (without the mime parts and version) e.g. format=structurespecificdata.xml |
| version | SDMX version, whatever is supported via Accept [version] |

**Comment by sosna** [comment]
Agreed to:

- Leave it out of the API
- Add a page on the Wiki on how to extend the API, and use the format parameter as an example

**Comment by sosna** [comment]
Closed, as the Wiki page [has now been created](https://github.com/sdmx-twg/sdmx-rest/wiki/Extending-the-restful-api) (thanks @stratosn!).
