### ISSUE TITLE
Usage examples for the metadata resource.

### ISSUE THREAD

**Issue by dur41d** [sdmx-twg/sdmx-rest#37]
While there are many examples of how to use the /data resource, I could not find any about  the /metadata. The SDMX Web Services Guidelines has only information and examples for /data (see section 4.4.3). 

Please redirect me to any resources that would explain how to retrieve reference metadata using REST and especially how to use the ‘key’ parameter as defined by the wadl. 

Thanks.

**Comment by sosna** [comment]
Will be addressed by #46
