### ISSUE TITLE
API Down

### ISSUE THREAD

**Issue by Alonreznik** [sdmx-twg/sdmx-rest#43]
Hi There.
I'm trying to get data from the Rest API, with your example as it exists in your docs.
The call is GET https://sdw-wsrest.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?startPeriod=2009-05-01&endPeriod=2009-05-31

The Rest API return internal error (status code 500) without any error description.

Please fix it.

Thanks!

**Comment by Tzaphkiel** [comment]
Dear Alonreznik,

This repository hosts the SDMX Technical Working Group's work on the standard itself.

We are not in a position where we can provide you with help on this _"Internal Server Error" (HTTP_500)_ as the web service belongs to the [_European Central Bank_](http://www.ecb.europa.eu/home/html/index.en.html). 

I also believe that there was a planned go-live of a new release over the course of this week-end.
I have tried the URL twice (once before this message and it indeed failed) and again now (and it works).

I suggest that you please contact the **ECB's hotline** instead at the following address:

- https://sdw.ecb.europa.eu/web/generator/docu/SDWHelpExt/contacts.html

Kind regards
Sébastien

**Comment by Alonreznik** [comment]
Hi Sébastien!
Thanks for your comment.

I'll contact with the ECB.

Sincerely, 
Alon
