### ISSUE TITLE
Improve documentation about start and endPeriod in the Wiki

### ISSUE THREAD

**Issue by sosna** [sdmx-twg/sdmx-rest#44]
Handling of the start and end periods might depend on the values of the collection attribute (such as beginning, middle, average or end of period).

This is not reflected in the documentation at the moment, but it would be valuable information for implementers.

**Comment by ZoharLiran** [comment]
@sosna this is exactly what I am looking for. can you please refer me to a location in which I can find how to add to the query JSON the startPeriod and endPeriod?
Thank you

**Comment by sosna** [comment]
A paragraph has been added to the [Data queries Wiki page](https://github.com/sdmx-twg/sdmx-rest/wiki/Data-queries). However, collection attribute has not been taken into account. The start and end periods merely express a range and therefore, start period should be considered as being the 1st instant in that period, while end period should be considered the last one.
