### ISSUE TITLE
002-Support reference metadata

### ISSUE THREAD

**Issue by dosse** [sdmx-twg/sdmx-rest#46]
In order to allow easily retrieving referential metadata attached to any structural artefact or to data, it is proposed to extend the Rest API in the following way (this extension was already implemented by MT):

Prefixe any data and structure query with the path parameter '**metadata**', e.g.:

_protocol://ws-entry-point/codelist/IMF/CL_FREQ_  - returns codelist Frequency

_protocol://ws-entry-point/metadata/codelist/IMF/CL_FREQ_  - returns any reference metadata for the codelist Frequency (or any codes contained in the Codelist)

_protocol://ws-entry-point/data/BIS,EXR,1.0/N.AR._ - returns exchange rate dataset

_protocol://ws-entry-point/metadata/data/BIS,EXR,1.0/N..AR._ - returns the referential metadata for the dataset and for any series or observations contained in the dataset

This new syntax should replace the current more restrictive syntax:
_protocol://ws-entry-point/metadata/flowRef/key/providerRef_

**Comment by sosna** [comment]
Make sure the new version includes documentation (cf. #37) .
