### ISSUE TITLE
Added media types for SDMX-JSON & SDMX-CSV

### ISSUE THREAD

**Issue by dosse** [sdmx-twg/sdmx-rest#49]
Could an example of the Accept header for SDMX-JSON format (application/vnd.sdmx.data+json) please be added to the  4_6_conneg.md?

**Comment by sosna** [comment]
Yes.
As discussed, the following will be added:
* `application/vnd.sdmx.data+json;version=1.0.0`
* `application/vnd.sdmx.data+csv;version=1.0.0`

**Comment by sosna** [comment]
Addressed in the upcoming v1.3.0 release
