### ISSUE TITLE
Support Retrieval of Content Constraints by Type

### ISSUE THREAD

**Issue by agent96** [sdmx-twg/sdmx-rest#54]
A SDMX Content Constraint can have 2 distinct flavours – actual and allowable. Each flavour can fall into one of two categories (Keyset of Cube Region).  

In a way a Content Constraint should be at least 2 different maintainable objects, which can be independently retrieved, but if they remain as one object type in the next version of the standard, it would be useful at the API level to be able to distinguish between them.

In the same way the REST API allows the user to query for organisationscheme (which brings back agency, data provider, and data consumer schemes). It would be nice to add two new resource parameters to the API:

allowableconstraint
actualconstraint

 It is interesting to note that the actualconstraint may even be a bit redundant considering other requests (e.g. #40).  The actual constraint says what data actually exists, this could be a keyset (list of series) or cube region.  However for the former (keyset)  it is an incredibly verbose response, a much less verbose (and more flexible) client to server query is for the all data with detail=seriesKeysOnly.  The second query, cube region, may lose importance when bug #40 is resolved.  So for this purpose the Fusion Registry has already re-purposed the actualconstraint as a way to create sub-cube (pre-defined query) definitions - a use case we have been asked to support on many occasions.  The actual constraint is a useful mechanism for the client to build pre-selections for large dataflows, and hence the driver for us, to be able to distinguish between constraint used to restrict content for submission, to those that are used for dissemination.

**Comment by sosna** [comment]
The specific type (allowable | actual) would not help with identification, as agencyId, id and version remain sufficient for this purpose (like for all maintainable artefacts). However, it would help filtering out constraints that are not of the desired type (for example, if you care only about actual content, you are not interested in retrieving constraints describing allowable content).

**Comment by sosna** [comment]
This will be supported by the additions of 2 new REST resources: actualconstraint and allowedconstraint.

**Comment by sosna** [comment]
Addressed in the upcoming v1.3.0 release
