### ISSUE TITLE
Switch API definition from WADL to newer open specification

### ISSUE THREAD

**Issue by Tzaphkiel** [sdmx-twg/sdmx-rest#57]
The definition of the WS API should be updated into a newer format.

Potential candidates are: 

- [Open API Spec 3.0.0](https://github.com/OAI/OpenAPI-Specification) (old swagger 2.0 evolution)
- [RAML](https://github.com/raml-org/raml-spec) (proprietary?!)
- [Postman collections](http://schema.getpostman.com/?_ga=2.57786666.1285496565.1516107910-693506847.1513672098)
- ...?

A potential outcome or distributed would be the equivalent set of Postman collections that could be used to test the Web Services. Another would be a Swagger or RAML documentation web site.

**Comment by sosna** [comment]
The list of compliant APIs could be listed in the server block: https://swagger.io/docs/specification/api-host-and-base-path/

**Comment by sosna** [comment]
Available in v1.5.0 of the API
