### ISSUE TITLE
Add support for updatedAfter to metadata queries

### ISSUE THREAD

**Issue by sosna** [sdmx-twg/sdmx-rest#68]
When querying for data, a client has the possibility to indicate that it wants to retrieve what has changed since a certain point in time. 

It would be nice to add a similar feature to metadata queries.

The fact that metadata messages do not have the equivalent of a dataset action might be an issue, though.

**Comment by sosna** [comment]
Good point indeed! It sounds logical to me that updatedAfter applies to anything matching the query. On the other hand, asking for a *datastructure* resource and then getting a response without any *datastructure* in it, but only *codelists* does not seem ideal...

**Comment by stratosn** [comment]
Would this issue potentially include adding such information (i.e. lastUpdated) in the Maintainables?

**Comment by sosna** [comment]
We might want to rethink the use cases again and see whether existing HTTP features (like conditional GET requests) might be sufficient.

**Comment by sosna** [comment]
With the next release of the API, the following “time-related” features will be available for data queries:
 
- Retrieve the current version of the data (i.e. the default behaviour)
- Retrieve the current version of the data but only if something has changed (using HTTP feature like `If-Modified-Since` or `If-None-Match`)
- Retrieve the data that have changed since a certain point in time (using `updatedAfter`)
- Retrieve how the data evolved over time (using `includeHistory`)
- Retrieve how the data were at a certain point in time (using `asOf`)
 
For structure queries, we have the following:
- Retrieve the current state of an artefact
- Retrieve the current state of an artefact but only it has changed 
- Retrieve how the artefact was at a certain point in time
 
In short, we don’t have:
- Retrieve what has changed since a certain point in time (updatedAfter)
- Retrieve how an artefact evolved over time (withHistory)
 
The understanding is that this is OK for the following reasons:
- How an artefact evolved over time is expected to be handled via semantic versioning nowadays.
- `updatedAfter` seems rather difficult. We could of course only return the changes made to, say, a codelist, but that would required adding information about the action too (for example, codes X, Y and Z have been added, while code A has been deleted). In short, it seems quite complex (i.e. something similar to the Registry synchronization mechanism between 2 registries). Also, while item schemes can indicate that they are “partial”, I don’t think this is true for other types of artefacts like, say, a DSD (in case we want to say that this attribute has been added, as this dimension has a new max_length facet)…

Therefore, this issue will be closed
