### ISSUE TITLE
Add option to query for number of data points to be delivered

### ISSUE THREAD

**Issue by egreising** [sdmx-twg/sdmx-rest#69]
In many use cases, knowing in advance the number of observations to be delivered by a data query may be very useful as it allow you to warn the user about "no data available" or excessive information (e.g. greater than a certain threshold)  situations without having to wait for the actual data query to be completed.
It worth noting that in most databases, the query for "count" returns the amount of tuples in an invariant time, regardless of the amount of data.
The proposal is to add a new possible value "count" for the "detail=" parameter in the data query. When "detail=count" is specified, the number of observations to be returned by the query is returned.
For the returned message, the simplest way would be to return just the number of observations, regardless of the message format in effect. This has the advantage of being format independent and, as a matter of fact, if somebody is querying for the count, nothing else really matters. Besides, it will be faster, as the writer has no need to format a message. Especially in JSON, there's no need to query for the structural metadata to include.
Otherwise, if the message structure will be kept for the information returned, the count would require the definition of new optional elements in the message header of XML and in the meta of JSON formats to place the count, and some way should be agreed for the CSV data message to return the count.
TF3 (Message formats) should advise on these points.

**Comment by dosse** [comment]
Maybe this could be achieved simply using the slicing mechanism, see issue #50 "Allow slicing of data messages". E.g. the request could include an accept header of "Range: values=1-1" asking for only the first value (I'm not sure "Range: values=0-0" would be acceptable). The response will then return that first (or no) observation together with the number of available observations in the HTTP header "Content-Range: values 1-1/1234" indicating that 1234 is the number of available observations.

**Comment by egreising** [comment]
> Maybe this could be achieved simply using the slicing mechanism, see issue #50 "Allow slicing of data messages". E.g. the request could include an accept header of "Range: values=1-1" asking for only the first value (I'm not sure "Range: values=0-0" would be acceptable). The response will then return that first (or no) observation together with the number of available observations in the HTTP header "Content-Range: values 1-1/1234" indicating that 1234 is the number of available observations.

Yes, this work-around can also serve the purpose of getting the total count of values. However I think that the count of values is a very useful information that would not be so easy to obtain by this mechanism, which requires access to the Range header field when submitting the URL (not possible to handle in every environment, for example with a browser), but also will require accessing and parsing the http header  of the returned message. In my point of view, having the "details=count" in the API and adding a new element in the message does not require too much effort, would not have any impact in terms of compatibility and would be much easier to manage by any user.

**Comment by dosse** [comment]
This feature seems being covered in SDMX 3.0.0 by the `obs-count` annotation in the actual content constraints returned by the availability queries.

**Comment by sosna** [comment]
@egreising, indeed, as mentioned by @dosse, availability queries support the use case. So, I'll close the issue but let us know in case you have questions or suggestions.
