### ISSUE TITLE
Support Registration Query

### ISSUE THREAD

**Issue by agent96** [sdmx-twg/sdmx-rest#71]
Currently the only SDMX Artifact that can not be retrieved via REST is the Data Registration.  This will be useful for applicaitons that wish to have knowledge of where the data is located, enabling applications to browse the metadata, and then get related datasets via the Registration message.

A proposed solution is to be able to retrieve registraitons by

- Agency/Id

- Dataflow / Provision Agreement

- Data Provider

For input to this discussion, we have added support into the Fusion Registry, please refer to section 3.6 in the [following document](https://metadatatechnology.com/assets/Custom/documentation/100_Fusion%20Registry%209%20Enterprise%20Edition/100_Fusion%20Registry%20Enterprise%20Edition%20Release%209.2/Web-services%20guide.pdf#page=26)

**Comment by sosna** [comment]
Was possible with SOAP but SOAP has been deprecated

**Comment by agent96** [comment]
Proposal Attached
[Issue71_RegistrationQuery.docx](https://github.com/sdmx-twg/sdmx-rest/files/8649952/Issue71_RegistrationQuery.docx)

**Comment by agent96** [comment]
[Issue71_RegistrationQuery_V2.docx](https://github.com/sdmx-twg/sdmx-rest/files/8650076/Issue71_RegistrationQuery_V2.docx)

**Comment by sosna** [comment]
Fixed in v2.1.0
