### ISSUE TITLE
Version the API

### ISSUE THREAD

**Issue by sosna** [sdmx-twg/sdmx-rest#90]
Should we propose a way to version the API? It's considered good practice, and it brings additional guarantees to clients.

Considering SDMX adoption of semantic versioning, we could limit the versioning to the MAJOR segment of the version (e.g. v1, v2, v3, etc.) as MINOR and PATCH changes should not have an impact on clients.

**Comment by Tzaphkiel** [comment]
I am all for it.
Let's go full throttle and also provide a way to discover the API as well (HATEOAS?) ;-)

**Comment by dosse** [comment]
👍

**Comment by sosna** [comment]
A recommendation has been added to the [Wiki](https://github.com/sdmx-twg/sdmx-rest/wiki/Tips-for-providers).
