### ISSUE TITLE
Question: Rate Limits

### ISSUE THREAD

**Issue by felixhagspiel** [sdmx-twg/sdmx-rest#99]
Our server is pulling exchange rates data once per day (data for the last 7 days / CSV / no detailed metadata), but due to timezone differences and the time until the exchange rate of the current day (i.e. on weekends) is available our server does a few more request around midnight.

Also, we have automated tests which may lead into pulling data from your API a few hundred (or thousand) times within 2-3 hours.

I wanted to know if there are any rate limits? And if so, where can I find them or can I somehow get the current limits via your API?

**Comment by sosna** [comment]
This GitHub repository is used to maintain the specification itself. We are not aware of all the organizations that implement the specification, and we also don't know any particular limit that these organizations have put in place.

So, it's not clear to me which service you are targeting (ECB, Eurostat, OECD, etc., etc.) but, in any case, I'd suggest contacting the owners of that particular service directly .
